server:
  port: 8005



spring:
  application:
    name: cloud-link

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.15.86:8848
        username: nacos
        password: nacos



#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



